language: node_js
node_js: "10.15"
cache: yarn

stages:
  - name: test

  - name: production-started
    if: tag =~ /^v\d+\.\d+\.\d+$/
  - name: production
    if: tag =~ /^v\d+\.\d+\.\d+$/
  - name: production-finished
    if: tag =~ /^v\d+\.\d+\.\d+$/

  - name: staging-started
    if: tag is present
  - name: staging
    if: tag is present
  - name: staging-finished
    if: tag is present

jobs:
  include:
    - stage: test
      env: [NODE_ENV=test]

    - stage: production-started
      name: Deployment Started
      script: npx @base-cms/website-deployment-tool notify-started
      install: skip
      env: [ENVIRONMENT=production RANCHER_CLUSTERID=c-gxsr7]

    - stage: staging-started
      name: Deployment Started
      script: npx @base-cms/website-deployment-tool notify-started
      install: skip
      env: [ENVIRONMENT=staging RANCHER_CLUSTERID=c-rc5kp]

    #############################
    ### vvv ADD SITES HERE vvv ##
    #############################

    - stage: production
      name: greenindustrypros.com
      script: npx @base-cms/website-deployment-tool deploy greenindustrypros.com caprica
      install: skip
      env: [ENVIRONMENT=production RANCHER_CLUSTERID=c-gxsr7]

    - stage: staging
      name: greenindustrypros.com
      script: npx @base-cms/website-deployment-tool deploy greenindustrypros.com caprica
      install: skip
      env: [ENVIRONMENT=production RANCHER_CLUSTERID=c-rc5kp]

    - stage: production
      name: sdcexec.com
      script: npx @base-cms/website-deployment-tool deploy sdcexec.com caprica
      install: skip
      env: [ENVIRONMENT=production RANCHER_CLUSTERID=c-gxsr7]

    - stage: staging
      name: sdcexec.com
      script: npx @base-cms/website-deployment-tool deploy sdcexec.com caprica
      install: skip
      env: [ENVIRONMENT=production RANCHER_CLUSTERID=c-rc5kp]

    - stage: production
      name: mixequipmentmag.com
      script: npx @base-cms/website-deployment-tool deploy mixequipmentmag.com caprica
      install: skip
      env: [ENVIRONMENT=production RANCHER_CLUSTERID=c-gxsr7]

    - stage: staging
      name: mixequipmentmag.com
      script: npx @base-cms/website-deployment-tool deploy mixequipmentmag.com caprica
      install: skip
      env: [ENVIRONMENT=production RANCHER_CLUSTERID=c-rc5kp]

    #############################
    ### ^^^ ADD SITES HERE ^^^ ##
    #############################

    - stage: production-finished
      name: Deployment Finished
      script: npx @base-cms/website-deployment-tool notify-finished
      install: skip
      env: [ENVIRONMENT=production RANCHER_CLUSTERID=c-gxsr7]

    - stage: staging-finished
      name: Deployment Finished
      script: npx @base-cms/website-deployment-tool notify-finished
      install: skip
      env: [ENVIRONMENT=staging RANCHER_CLUSTERID=c-rc5kp]
