language: node_js
node_js: "10.15"
cache: yarn

stages:
  - name: test
  - name: notify_start
    if: tag is present
  - name: deploy
    if: tag is present
  - name: notify
    if: tag is present

jobs:
  include:
    - stage: test
      env:
        - NODE_ENV=test

    - stage: notify_start
      script: deploy/notify-start.sh
      install: skip

    - stage: notify
      script: deploy/notify.sh
      install: skip

    - stage: deploy
      name: Aviation Pros
      script: deploy/index.js greenindustrypros caprica
      install: skip
